services:
  app:
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    environment:
      - PORT=5173
    command: pnpm dev --host 0.0.0.0 --port 5173
    restart: unless-stopped
volumes:
  node_modules:
  pnpm-store:
